# 0001_NumPy_Basic

---

[NumPy Basic](https://www.w3resource.com/python-exercises/numpy/basic/index.php)

---

### 1. Write a Numpy program to get the Numpy version and show the Numpy build configuration. 

Import the numpy library:
This line imports the numpy library and assigns it the alias **np** for convenience.

In [1]:
import numpy as np

Print the numpy version:
This line prints the version of the numpy library using the `__version__` attribute. It displays the version number of numpy installed in your Python environment.

In [2]:
print(np.__version__)

1.20.1


Print the **numpy** configuration:


In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


---

---

### 2. Write a NumPy program to get help with the add function. 

In [6]:
import numpy as np

This line uses the np.info() function to display detailed information about the numpy.add function.

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

---

---

### 3. Write a NumPy program to test whether none of the elements of a given array are zero.  

In [8]:
import numpy as np

In [9]:
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

In [10]:
# Test whether none of the elements are zero
result = np.all(array != 0)

`array != 0`: This part of the expression creates a boolean array of the same shape as array. Each element in this boolean array will be True if the corresponding element in the array is not equal to zero and False otherwise. In other words, it checks element-wise if the elements in array are not equal to zero.

`np.all()`: This is a NumPy function called **all**. It checks whether all elements in a boolean array are True. If all elements in the boolean array are True, np.all returns True. If at least one element in the boolean array is False, it returns False.

In [11]:
# Print the result
if result:
    print("None of the elements in the array are zero.")
else:
    print("At least one element in the array is zero.")

None of the elements in the array are zero.


---

---

### 4. Write a NumPy program to test if any of the elements of a given array are non-zero.  

In [19]:
import numpy as np

In [20]:
# Create a NumPy array
array = np.array([0, 0, 0, 1, 0])

In [21]:
# Test if any element in the array is non-zero
result = np.any(array != 0)

We use the expression `array != 0` to create a boolean array where each element is True if the corresponding element in the original array is non-zero and False if it's zero.

We use the `np.any()` function to check if at least one element in the boolean array is True, indicating that there is at least one non-zero element in the original array.

In [22]:
# Print the result
if result:
    print("At least one element in the array is non-zero.")
else:
    print("All elements in the array are zero.")

At least one element in the array is non-zero.


---

---

### 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number). 

In [23]:
import numpy as np

In [24]:
# Create a NumPy array with some finite and non-finite elements
array = np.array([1.0, 2.0, np.inf, np.nan, -np.inf])

In [25]:
# Test for finiteness element-wise
result = np.isfinite(array)

The `np.isfinite()` function check the finiteness of each elemente. The result is a boolean array, where True indicates that the corresponding element is finite, and False indicates that it's either infinity or a NaN

In [26]:
# Print the result
print("Original array:")
print(array)

Original array:
[  1.   2.  inf  nan -inf]


In [27]:
print("Is finite (not infinity or NaN) element-wise:")
print(result)

Is finite (not infinity or NaN) element-wise:
[ True  True False False False]


---

---

### 6. Write a NumPy program to test elements-wise for positive or negative infinity.  

In [28]:
import numpy as np

In [29]:
# Create a NumPy array with some elements including positive and negative infinity
array = np.array([1.0, np.inf, -np.inf, 2.0, -np.inf, np.nan])

In [30]:
# Test for positive infinity element-wise
is_pos_inf = np.isposinf(array)

In [31]:
# Test for negative infinity element-wise
is_neg_inf = np.isneginf(array)

In [36]:
# Test for infinity positive or negative
is_inf_inf = np.isinf(array)

In [32]:
# Print the results
print("Original array:")
print(array)

Original array:
[  1.  inf -inf   2. -inf  nan]


In [33]:
print("Is positive infinity element-wise:")
print(is_pos_inf)

Is positive infinity element-wise:
[False  True False False False False]


In [34]:
print("Is negative infinity element-wise:")
print(is_neg_inf)

Is negative infinity element-wise:
[False False  True False  True False]


In [37]:
print("Is positive OR negative infinity element-wise:")
print(is_inf_inf)

Is positive OR negative infinity element-wise:
[False  True  True False  True False]


---

---

### 7. Write a NumPy program to test element-wise for NaN (Not-a-Number)  of a given array. 

In [38]:
import numpy as np

In [39]:
# Create a NumPy array with some elements including NaN
array = np.array([1.0, np.nan, 2.0, 3.0, np.nan, 4.0])

In [40]:
# Test for NaN element-wise
is_nan = np.isnan(array)

In [43]:
# Print the results
print("Original array:")
print(array)

Original array:
[ 1. nan  2.  3. nan  4.]


In [44]:
print("Is NaN element-wise:")
print(is_nan)

Is NaN element-wise:
[False  True False False  True False]


---

---

### 8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.  

In [29]:
import numpy as np

In [30]:
# Create a sample NumPy array
sample_array = np.array([1, 2 + 3j, 3.5, 4, 5.5 + 2j])

In [31]:
# Test for complex numbers
is_complex = np.iscomplex(sample_array)

In [32]:
# Test for real numbers
is_real = np.isreal(sample_array)

In [33]:
# Test if a given number is of a scalar type
given_number = 7
is_scalar = np.isscalar(given_number)

In [34]:
# Print the results
print("Original Array:")
print(sample_array)

Original Array:
[1. +0.j 2. +3.j 3.5+0.j 4. +0.j 5.5+2.j]


In [35]:
print("Element-wise test for complex numbers:")
print(is_complex)

Element-wise test for complex numbers:
[False  True False False  True]


In [36]:
print("Element-wise test for real numbers:")
print(is_real)

Element-wise test for real numbers:
[ True False  True  True False]


In [37]:
print("Is the given number a scalar?")
print(is_scalar)

Is the given number a scalar?
True


---

---

### 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 

Note: The tolerance values are positive, typically very small numbers. The relative difference `(rtol * abs(b))` and the absolute difference atol are added together to compare against the absolute difference between a and b.

In [38]:
import numpy as np

In [39]:
# Create two NumPy arrays
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.0, 2.001, 3.0])

In [40]:
# Define a tolerance level
tolerance = 0.01

In [41]:
# Test whether the two arrays are element-wise equal within the specified tolerance
are_equal = np.allclose(array1, array2, atol=tolerance)

In this example, we have two NumPy arrays array1 and array2. We use the np.allclose() function to test whether the elements in these arrays are equal within the specified tolerance (tolerance), and the result is printed based on the comparison. If the elements in the arrays are equal within the tolerance, it will print that the arrays are element-wise equal within the tolerance; otherwise, it will print that they are not.

In [42]:
# Print the result
if are_equal:
    print("The arrays are element-wise equal within the tolerance.")
else:
    print("The arrays are not element-wise equal within the tolerance.")

The arrays are element-wise equal within the tolerance.


---

---

### 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays. 

In [43]:
import numpy as np

In [44]:
# Create two NumPy arays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 2, 2, 4, 6])

In [45]:
# Element-wise greater comparison
greater_comparison = array1 > array2

In [46]:
# Element-wise greater_equal comparison
greater_equal_comparison = array1 >= array2

In [47]:
# Element-wise less comparison
less_comparison = array1 < array2

In [48]:
# Element-wise less_equal comparison
less_equal_comparison = array1 <= array2

In [49]:
# Print original arrays
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [1 2 3 4 5]
Array 2: [3 2 2 4 6]


In [50]:
print("\nElement-wise Greater Comparison:")
print(greater_comparison)


Element-wise Greater Comparison:
[False False  True False False]


In [51]:
print("\nElement-wise Greater Equal Comparison:")
print(greater_equal_comparison)


Element-wise Greater Equal Comparison:
[False  True  True  True False]


In [52]:
print("\nElement-wise Less Comparison:")
print(less_comparison)


Element-wise Less Comparison:
[ True False False False  True]


In [53]:
print("\nElement-wise Less Equal Comparison:")
print(less_equal_comparison)


Element-wise Less Equal Comparison:
[ True  True False  True  True]


---

---

### 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [54]:
import numpy as np

In [58]:
array1 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
array2 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

In [59]:
# Element-wise equality comparison
equal_comparison = np.equal(array1, array2)

In [60]:
print(equal_comparison)

[ True  True  True  True  True  True  True  True  True False]


In [61]:
# Define a numerical tolerance
tolerance = 0.1

In [62]:
# Element-wise equality within a tolerance comparison
equal_within_tolerance = np.isclose(array1, array2, rtol=tolerance)

In [63]:
print(equal_within_tolerance)

[ True  True  True  True  True  True  True  True  True  True]


---

---

### 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 

In [64]:
import numpy as np

In [65]:
# Create a NumPy array with the given values
my_array = np.array([1, 7, 13, 105])

In [66]:
# Determine the size of the memory occupied by the array
memory_size = my_array.nbytes

In [67]:
# Print the array and its memory size
print("Array:", my_array)
print("Memory Size (in bytes):", memory_size)

Array: [  1   7  13 105]
Memory Size (in bytes): 16


---

---

### 13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.  

In [68]:
import numpy as np

In [69]:
# Create an array of 10 zeros
zeros_array = np.zeros(10)

In [70]:
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [71]:
# Create an array of 10 ones
ones_array = np.ones(10)

In [72]:
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [77]:
# Create an array of 10 fives
fives_array = np.full(10, 5)

In [78]:
print(fives_array)

[5 5 5 5 5 5 5 5 5 5]


In [79]:
# Create an array of 10 fives
fives_array = np.full(10, 5.0, dtype=float)

In [80]:
print(fives_array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [81]:
# Concatenate the three arrays to create the final array
result_array = np.concatenate((zeros_array, ones_array, fives_array))

In [82]:
print(result_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


---

---

### 14. Write a NumPy program to create an array of integers from 30 to 70. 

In [83]:
import numpy as np